### ISSUE TITLE
关于requirements

### ISSUE THREAD

**Issue by ly934060690** [zgzjdx/Chinese_Main_Location_Extraction#1]
“A Chinese Main Location Extraction Method based on IDLSTM+CRF”论文作者，您好！
我想复现论文结果，包含训练、验证、测试、预测等，请问我的py环境应该怎样设定？
可否能将requirements导出一份上传GitHub呢？

比较着急，收到此Issues恳请作者即使回复下，辛苦了，谢谢！

LIU Y

**Comment by zgzjdx** [comment]
The main dependency of this repo is Tensorflow 1.13.1. I have responded this issue via personal email.

**Comment by ly934060690** [comment]
嗯嗯，收到啦，谢谢作者！
